sudo: required
services:
  - docker

before_install:
  - docker build -t tolunardahanli/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true tolunardahanli/react-test npm test

after_success: # after_success test build prod images
  - docker build -t tolunardahanli/multi-client ./client
  - docker build -t tolunardahanli/multi-nginx ./nginx
  - docker build -t tolunardahanli/multi-server ./server
  - docker build -t tolunardahanli/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  
  # Take those images and push them to dockerHub
  - docker push tolunardahanli/multi-client
  - docker push tolunardahanli/multi-nginx
  - docker push tolunardahanli/multi-server
  - docker push tolunardahanli/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-115591746071"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY